export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/register'
export const BASKET_ROUTE = '/basket'
export const FAVORITE_ROUTE = '/favorite'
export const HOME_ROUTE = '/'
export const PRODUCT_ROUTE = '/picture'
export const ORDER_ROUTE = '/order'